# Project: AirportManagement
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o Plane.o Airport.o Helicopter.o
LINKOBJ  = main.o Plane.o Airport.o Helicopter.o
LIBS     = -L"C:/Users/Admin/Dev-Cpp/MinGW64/lib" -L"C:/Users/Admin/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Admin/Dev-Cpp/MinGW64/include" -I"C:/Users/Admin/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Admin/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Admin/Dev-Cpp/MinGW64/include" -I"C:/Users/Admin/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Admin/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Admin/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = AirportManagement.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Plane.o: Plane.cpp
	$(CPP) -c Plane.cpp -o Plane.o $(CXXFLAGS)

Airport.o: Airport.cpp
	$(CPP) -c Airport.cpp -o Airport.o $(CXXFLAGS)

Helicopter.o: Helicopter.cpp
	$(CPP) -c Helicopter.cpp -o Helicopter.o $(CXXFLAGS)
